[build]
  command = "deno task build"
  publish = "site/_lume/dist"

[[headers]]
  for = "/fonts/*"
  [headers.values]
  cache-control = "max-age=604800" # 1 week

[[headers]]
  for = "/images/*"
  [headers.values]
  cache-control = "max-age=604800" # 1 week

[[headers]]
  for = "/favicon.ico"
  [headers.values]
  cache-control = "max-age=604800" # 1 week

[[redirects]]
  from = "/guide/inline-queries.html"
  to = "/plugins/inline-query"
  status = 301

[[redirects]]
  from = "/*/guide/inline-queries.html"
  to = "/:splat/plugins/inline-query"
  status = 301

[[redirects]]
  from = "/advanced/*"
  to = "/en/advanced/:splat"
  status = 301

[[redirects]]
  from = "/demo/*"
  to = "/en/demo/:splat"
  status = 301

[[redirects]]
  from = "/guide/*"
  to = "/en/guide/:splat"
  status = 301
  
[[redirects]]
  from = "/hosting/*"
  to = "/en/hosting/:splat"
  status = 301
  
[[redirects]]
  from = "/plugins/*"
  to = "/en/plugins/:splat"
  status = 301
  
[[redirects]]
  from = "/resources/*"
  to = "/en/resources/:splat"
  status = 301
  
[[redirects]]
  from = "/index.html"
  to = "/en/:splat"
  status = 301

[[redirects]]
  from = "/en/*"
  to = "/en/404.html"
  status = 404

[[redirects]]
  from = "/es/*"
  to = "/es/404.html"
  status = 404

[[redirects]]
  from = "/id/*"
  to = "/id/404.html"
  status = 404

[[redirects]]
  from = "/uk/*"
  to = "/uk/404.html"
  status = 404

[[redirects]]
  from = "/zh/*"
  to = "/zh/404.html"
  status = 404

[[redirects]]
  from = "/*"
  to = "/en/404.html"
  status = 404